### ISSUE TITLE
Stretnutie s cvičiacim

### ISSUE THREAD

**Issue by danasko** [TIS2017/Kurzy#1]
stretnutie s cviciacim 6.10.

**Comment by pavelpetrovic** [comment]
dobrý deň, teším sa, že napredujete, ale zápisnice, prosím, nedávajte do repozitára, ale priamo píšte na stretnutí do wiki. inšpirujte sa, ako to je aj v iných projektoch (sú v tej istej organizácii, takže ich ľahko nájdete), napr. tu (hoci je to len zápisnica s cvičiacim, ale funguje to podobne): https://github.com/TIS2017/DiscGolf/wiki/%C3%9Avodn%C3%A9-stretnutie-6.10.2017
Cvičiaci asi robí zápisnicu so stretnutia s vami, pre seba aj pre vás, ale je to na ňom ako. 

preto túto zápisnicu z repozitára vymažte, vytvorte to na wiki a aj ďalšie zápisnice robte tam. ďakujem.
oceňujem, že ste na zápisnicu spravili issue, v princípe asi stačí jeden issue na všetky zápisnice, ale to je na vás. veľa zdaru.

Pavel.

**Comment by andrejjursa** [comment]
@TIS2017/aaaa Je mozne, ze sme na to na stretnuti zabudli, kedze sme behali kade-tade a nakoniec skor riesili to PHP, ale pre buducnost, zapisnice davame na wiki a dokumentaciu do adresara /documentation do repozitara (najlepsie vo formate pdf).
