### ISSUE TITLE
Naštudovanie dokumentácie použitých technológií

### ISSUE THREAD

**Issue by marmanova3** [TIS2017/Kurzy#10]
Symfony:
- https://symfony.com/doc/current/index.html
- https://knpuniversity.com/screencast/symfony/start-project //dobré video tutoriály od základov

Doctrine: 
- http://docs.doctrine-project.org/en/latest/
- https://symfony.com/doc/current/doctrine.html 
- https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html //cudzie kľúče

MySQL:
- https://dev.mysql.com/doc/refman/5.7/en/
- https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems //rozdiely medzi PostgreSQL a MySQL

**Comment by andrejjursa** [comment]
K Doctrine v Symfony 3 toto vyzera celkom rozumne, seria 7 videi:
 - https://www.codereviewvideos.com/course/doctrine-databasics

Nieco na login cez Doctrine:
 - https://www.youtube.com/watch?v=3xhYwwznIWU
 - https://www.youtube.com/watch?v=4Mb3siIjrm8 (toto rozobera ako spravit registracny formular, to nebudete potrebovat ale pre uplnost davam link)
