### ISSUE TITLE
Tvorba IA systému a návrh GUI

### ISSUE THREAD

**Issue by marmanova3** [TIS2017/Kurzy#11]
Návrh v https://moqups.com.
Systém je potrebné priblížiť a zladiť s http://uniba.sk a http://dai.fmph.uniba.sk/w/Introduction/sk.

**Comment by marmanova3** [comment]
@Saamoot Nahrala som nový návrh rozhraní upravený podľa pripomienok z piatka. Môžeš na to, prosím ťa, pozrieť? Ale nie príliš dlho. Ďakujem :)

**Comment by Saamoot** [comment]
@marmanova3 pozrel som sa na to a poprosil by som o zmenu pri nasledovnych veciach.
Prilozene obrazky pouzit ako guideline a nie ako pravidlo, ze tak to musi vyzerat.


- stranka moje kurzy - prihlaseny na kurzy
  - pouzit taky isty vizual(taby) ako pri vypise dostupnych kurzov(menu polozka KURZY), ale defaultny tab je termin

- moje kurzy - absolvovane kurzy
  - chybaju kurzy ktore clovek absolvoval(zucastnil sa) ale nezvladol ich
  1, premenovat na "prihlasene kurzy" (alebo nieco v zmysle kurzy o ktore sa clovek pokusil)
    - dalej to bude rozdelene na uspesne a neuspesne kurzy
  2, premenovat na uspesne absolvovane kurzy
    - a pridat dalsiu polozku "neuspesne" absolvovane kurzy (lepsie slovo nez neuspesne ak vas napadne)
  3, do zoznamu absolvovanych kurzov  pridat informaciu o tom, ci clovek uspesne alebo neuspesne absolvoval kurz (asi najlepsia moznost)


- vedene kurzy - aktualne kurzy
  - odkaz "zoznam prihlasenych" zmenit na tlacitko "zoznam prihlasenych", ktore zobrazi "modal" okno po tom ako sa nan klikne
![kurzy_01](https://user-images.githubusercontent.com/10142060/33235289-957dad08-d235-11e7-9cd5-2a011df49a7b.PNG)

  - tlacitko "zoznam prihlasenych" premiestnit nad tlacitko "upravit"

- vedene kurzy - v minulosti
  - zoznam zucastnenuch tiez treba premenit na button, ktory bude otvarat "modal" okno a v nom bude vypis, ktory ste vytvorili
  - input na meno cloveka, pre ktoreho sa ma potvrdenie vytlacit aby mal autocomplete, ktory bude hladat v celom/plnom mene osoby

- novy termin kurzu
  - chyba vstup pre datum do kedy sa da odlasit
  - kapacita - dat input elementu type "number"
  - text "druh kurzu" zmenit na "novy termin pre kurz"
  - zjednotit vizualnu sirku vstupnych poli nech to nie je take kostrbate
  - input pre skolitela - aby mal autocomplete, ktory bude pri hladani hladat v celom/plnom mene osoby


- vytvor kurz
  - zjednotit vizualnu sirku vstupnych poli nech to nie je take kostrbate
  - namiesto odkazov na pridat dalsiu prerekvizitu dat talcitka
    - v pripade hard prerekvizity tlacitko bude otvarat modal okno, v kotorm bude filtrovatelny zoznam kurzov pri ktorych bude tlacitko vybrat a po kliknuti na tlacitko pridat sa prida kurz do zoznamu "hard preprekvizity"
  - input pre garanta - aby mal autocomplete, ktory bude pri hladani hladat v celom/plnom mene osoby
![kurzy_02](https://user-images.githubusercontent.com/10142060/33235293-a4ea854a-d235-11e7-8cc8-a8c8729f7674.PNG)


pridaj subadmin
 - zjednotit vizualnu sirku vstupnych poli nech to nie je take kostrbate
 - input pre subadmina - aby mal autocomplete, ktory bude pri hladani hladat v celom/plnom mene osoby
 - odkaz pridat dalsieho subadmina zmenit na tlacitko

**Comment by pavelpetrovic** [comment]
Ahojte,
Zmyslom konzultovania návrhu používateľského rozhrania so zákazníkom v našich projektoch je najmä overenie, či vývojári správne pochopili požiadavky dohodnuté v katalógu požiadaviek.
Preto pripomínam, že ak niečo nie je zachytené v schválenom katalógu požiadaviek, tak či to tím implementuje, alebo nie, je na ich slobodnom rozhodnutí, bez akejkoľvek bodovej straty. Neviem či je to ten prípad, ale môže sa to týkať napr. funkcionality typu autocomplete, vy budete vedieť posúdiť presnejšie. Samozrejme, nebránim CITu urobiť na ďalšie rozšírenia so študentami samostatnú dohodu o vykonaní práce.

Tiež požiadavky typu či tam bude tlačidlo alebo linka, treba brať ako želanie zákazníka, ktoré sa tím môže rozhodnúť splniť podľa toho, čo je ako pre tím technologicky/logisticky náročné.
Podobne, či niečo bude v modálnom dialógovom okne alebo na samostatnej stránke, je na rozhodnutí vývojového tímu, pokiaľ v kontrakte nemáme napísané niečo iné.

Cvičiacemu odporúčam, aby netrval na vytvorení ďalšej verzie návrhu používateľského rozhrania, pokiaľ ide o drobnosti - ide len o návrh, ktorého účelom bolo vytvoriť základnú predlohu pre implementáciu a získať spätnú väzbu od zákazníka, oboje je, myslím, splnené.

Tímu samozrejme odporúčam v rámci ich možností pri implementácii sa pokúsiť vyhovieť čo najväčšiemu množstvu želaní zákazníka.
Takže pokiaľ cvičiaci nebude komunikovať inak, tak tento návrh považujem za hotový, s tým, že komentáre zákazníka k nemu treba do dokumentu privesiť a v implementácii splniť podľa možností. Samozrejme, tím sa môže rozhodnúť vytvoriť aj novú verziu návrhu používateľského rozhrania. 
Ďakujem za dobrú spoluprácu!
Pavel.

**Comment by marmanova3** [comment]
@Saamoot zapracovali sme pripomienky

**Comment by Saamoot** [comment]
@marmanova3 prosim ta mozes mi niekam poslat odkaz na dokument, kde ste spravili zmeny ?

**Comment by marmanova3** [comment]
@Saamoot upravený dokument bol mimo priečinku dokumentácia už som to opravila, tu je link: https://github.com/TIS2017/Kurzy/blob/78a091a15963f293f57e28a86b4cd628f0ab2552/Documentation/Kurzy.pdf
