### ISSUE TITLE
Tvorba UML diagramov

### ISSUE THREAD

**Issue by marmanova3** [TIS2017/Kurzy#12]

**Comment by dandys2** [comment]
![UML class diagram](https://user-images.githubusercontent.com/25956904/32628394-fd980098-c595-11e7-8fd5-c8376df313ab.png)
zajtra sa na to ešte pozrieme spolu, treba dopisat metody a par detailov.

**Comment by pavelpetrovic** [comment]
všimol som si náčrt, tak pripíšem, že v triednom diagrame sa slovíčko extends podľa mňa nezvykne uvádzať, keďže to už vyjadruje ten prázdny trojuholníček a teda by išlo o zbytočnú duplicitu informácie. používa sa to v use-case ako stereotyp (medzi << a >>), lebo tam je to obyčajná šípka a môže tam byť namiesto toho aj iný stereotyp (<< include >>). ďakujem, p.
