### ISSUE TITLE
Vytvoriť testovacie scenáre

### ISSUE THREAD

**Issue by marmanova3** [TIS2017/Kurzy#13]
Prvý krok: zistiť čo sú testovacie scenáre a ako majú vyzerať.
Druhý krok: vytvoriť testovacie scenáre.

**Comment by spisakova31** [comment]
Testovacie scenare su všetky funkcie, ktoré je potrebné otestovať. 
Napr. skontrovat funkcionalitu prihlasenia, skontrolovat vytvorenie noveho kurzu, atd. 
Ku kazdemu scenaru treba aj pripravit testovaci pripad, nejake testovacie data (najlepsie take okrajove/netypicke/zle) a ocakavany vysledok

pozrite tento link, 
nie je toho vela 
http://www2.fiit.stuba.sk/~bielik/courses/psi-slov/slajdy/psi-manualne-testovanie2014.pdf 
hlavne slajdy 8-9

**Comment by pavelpetrovic** [comment]
moja predstava o testovacích scenároch je taký "dokument", ktorý by ste mohli dať nejakým najatým testovačom a podľa týchto dokumentov by výslednú aplikáciu mohli testovať. Príklad scenáru:

1. akcia: otvor hlavnú stránku aplikácie
výsledok: zobrazí sa hlavná stránka
2. akcia: zaregistruj nového používateľa (zadaj meno, mail)
výsledok: prišiel potvrdzovací mail, po kliknutí na linku v správe sa zobrazila stránka s overením potvrdenia
3. akcia: prihlás sa s novým používateľom
výsledok: zobrazí sa stránka s ponukou pre prihláseného používateľa
4. akcia: zobraz ponuku kurzov, zobraz podrobnosti o niektorom kurze
výsledok: zobrazí sa stránka s ponukou kurzov, po kliknutí na kurz sa zobrazia podrobné informácie o kurze
5. akcia: prihlás sa na kurz
výsledok...
atď.

Takýchto scenárov môže byť viacero a malo by platiť, že všetka funkcionalita, ktorá je vyžadovaná
v katalógu požiaviek, bude v niektorom zo scenárov pokrytá.

Nechceme vám veľmi pridávať prácu, takže to môže byť zapísané čo najstručnejšie a vo formáte
zrozumiteľnom vám a nie človeku, ktorý o systéme nič nevie.

Scenáre potom ale použijete na overenie, že aplikácia je ok.
To samé o sebe nebude stačiť, testovať treba viac, ale aspoň tieto základné testy
by sme potrebovali mať zapísané a určite overené.

Andrej ešte prípadne upresní, ako túto východiskovú predstavu chápe on a špecificky pre vás projekt.
Veľa úspechov!

**Comment by pavelpetrovic** [comment]
Andrea ma predbehla, kým som dopísal, v tom slajde je dôležitá poznámka, že tie dáta by mali byť čo najreálnejšie - nie len nejaké blablabla, ale radšej vymyslite konkrétne príklady dát podobné ako budú vyzerať v praxi. Podľa mňa to netreba do dokumentu písať, ak nechcete, stačí keď sa toho pravidla budete držať, vďaka.

**Comment by andrejjursa** [comment]
Mne sa celkom pozdavaju tie slajdy z FIIT, takto by sme to asi chceli mat. Co sa testovacich dat tyka, tak tam by nam malo stacit vytvorit si testovacie fixtures, ktore sa nacitaju do databazy v testovacom prostredi aplikacie pred kazdou testovacou procedurou, potom by do dokumentu, ked tak stacilo uviest nejaky ocakavany vstup pre test a aky ma byt vysledok.

Jedna poznamka k tomuto zo skusenosti s tymto predmetom: realizacia diela vacsinou dopadne trochu inak ako jeho navrh, co sa samozrejme potom koriguje v zaverecnej sprave, z tohoto dovodu je ale pred samotnym testovanim tiez nutne korigovat testovacie scenare a testovacie data, ocakavane vstupy a vystupy. Takze teoreticky mozete detaily o datach vypustit a doplnit ich do dokumentu, az ked budete naozaj testovat.

**Comment by spisakova31** [comment]
@andrejjursa  pridali sme hotove testovacie scenare
