### ISSUE TITLE
Tvorba katalógu požiadaviek

### ISSUE THREAD

**Issue by danasko** [TIS2017/Kurzy#4]
Rozdelenie: 

Michal: 1.1, 1.2, 1.5
Danka: 2.1, 2.2, 2.5
Aďka: 2.3, 2.4
Patrícia: 3.

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it moze my niekto vysvetlit co hladaju tie dokumenty docx a pdf mimo adresara dokumentacia, ked sme hovorili, ze vsetko co sa dokumentacie tyka ma byt v tomto adresari a nie inde?

Az budete mat dokument pripraveny na kontrolu, najskor ho poslite mne na schvalenie a az po mojom schvaleni ho mozete poslat dalej zadavatelovi.

**Comment by spisakova31** [comment]
Dobrý deň,

sú to iba také pracovné verzie, každý spravil časť dokumentácie, tak sme si
to hodili do branchu "katalog_poziadaviek". Tú finálnu verziu už chceme,
samozrejme, nahodiť do priečinku dokumentácia - tam sme už chceli mať pekné
hotové dokumenty. Alebo môžeme do toho priečinku dávať aj takéto pracovné
čiastkové verzie?

Dňa 16. októbra 2017, 14:18, Andrej Jursa <notifications@github.com>
napísal(-a):

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it spisem vam sem zhodnotenie dokumentu katalogu poziadaviek, ktore som vcera obdrzal emailom:

Nasledujuce plati pre cely dokument:

* ide o tlacovy dokument, taketo dokumenty sa pisu patkovym pismom, prosim aby ste toto opravili,
* uprava dokumentu ma niekolko problemov:
    1. nadpisy prvej urovne su centrovane na stred, prosim nastavte ich na zarovnanie do lava ako ostatne nadpisy,
    1. druhy problem s nadpismi prvej urovne je pridavanie bodky za cislo, to sa nerobi, sekcie sa neznacia radovimi cislami, tj. je 1 Uvod a nie 1. Uvod, nadpisy nizsich urovni mate ocislovane spravne,
    1. textove odstavce maju mat roztiahnutie na celu dlzku riadku, taketo kostrbate texty sa zle citaju a preto sa to nepouziva, tiez odsadenie prveho riadku v odstavci posobi divne, nepouziva sa to v technickych/vedeckych dokumentoch,
    1. celkova uprava je zalostna, na roznych miestach su texty pisane zdanlivo inym fontom alebo inou velkostou fontu, bohuzial to vyzera velmi zle, neviem ci to vzniklo nasledkom konvertovania do pdf ale trvam na tom, aby to bolo opravene a vsetky fonty boli unifikovane,
* v celom dokumente mi chybaju niektore deliace ciarky vo vetach, ktore tam podla gramatiky Slovenskeho jazyka maju byt,
* ak niekde v texte pouzivate slovo `uzivatel` tak ho prosim zmente na slovenske slovo `pouzivatel`, dakujem,
* dokument nie je ocislovany, pripominam ze cislovanie arabskymi cislicami zacina od strany, na ktorej je uvodna sekcia dokumentu.

A teraz k samotnym castiam dokumentu:

1. sekcia **1.1**, dokument nema riesit navrh, iba poziadavky a nie iba funkcne ale aj ostatne, tak isto co prosim vas je `webova aplikacia CIT`? Dokument nie je urceny pre pouzivatelov aplikacie, ale pre objednavatela a realizatorov diela,

1. sekcia **1.2**, v zasade obsah ok, len forma je trochu hovorova, velakrat pouzivate v jednom suveti rovnaku spojku (`ktora`, `ktory`, atd. - na sklonovani spojky nezalezi, zle sa to cita, ked sa opakuju po sebe), vyzadujem viac formalne zapisanie textu, nerozpravame to kamaratom pri obede ale popisujeme co system umozni pouzivatelom vykonavat za ukony, s textu je vsak zjavna iba urcita funkcionalita, mozno aj trochu dopletena, nie je vsak zjavny rozsah, bude lepsie ak tuto cast popisete vo viacerych odstavcoch, detailnejsie a formalne,

1. sekcia **1.3**, tu mam tiez nejake vyhrady: 
    1. vyklad skratky by mal zacinat malym pismenom a koncit ciarkov (pri poslednej skratke konci bodkov),
    1. niektore skratky nie su vysvetlene, je tam napisany iba ich nazov a v zatvorke nieco, co uplne nezodpoveda realite, priklad CSS3 by mohol byt popisany ako `technologia na jednotne stylovanie obsahu HTML dokumentu` a nie stroho `webova technologia`,
    1. `id` by chcelo trochu lepsi popis ako `identifikacia` (ako identifikacia coho, priklad.),

1. sekcia **1.4**, nie `stranka uniba` ale `stranka Univerzity Komenskeho v Bratislave` (plus bodky na konci viet),

1. sekcia **1.5**, opat velmi neformalne napisane, obsahovo ok, ale formu textu zmente tak, aby korespondovala s technickym dokumentom, tiez prosim vas kapitoly su v knihe a toto nie je kniha, tu to treba pomenovavat sekcie alebo casti, nepouzivat slovo `je` ale lepsie `nachadza sa`,

1. sekcia **2.1**, obsah ok, opat ta forma, opravit,

1. vo vasom pripade by mozno mohlo byt uzitocne zamenit poradie popisu **Funkcionality systemu** a **Specifikacii pouzivatelov**, kedze **Funkcionalita systemu** pramo pomenuva co moze robit ktora pouzivatelska rola,

1. sekcia **2.2**, v stlpci `Funkcionalita` zoznam technicky nasleduje za textom v prvom stlpci, cize kazdy prvok zoznamu ma zacinat malym pismenom a koncit ciarkov (posledny bodkov), naviac prosim nepouzivajte znak `/` ako nahradu za spojku `alebo` ale priamo pouzite tuto spojku (ako si iste vsimnete, pouzitie `/` sposobuje dlhe - nedelitelne - slova), dalej, tabulka musi mat oznacenie a musi na nu byt odkaz v texte, tj. prva veta by mala byt nieco v zneni *Prehlad funkcii, ktore webovy system poskytuje pouzivatelom, je zobrazeny v Tabulke 2.1.*,

1. sekcia **2.3**, obrazok nema ciselne oznacenie, pricom podla kontextu by mal mat cislo *2.1* pripadne *2.2* ak chapeme tabulky a obrazky ako rovnaky obsahovy prvok, nikde nie je na obrazok odkaz, hned sa hovori iba o konkretnych roliach pouzivatelov, posledna veta, ktora sa nachadza az na dalsej strane, by mala byt na zaciatku, lebo je velmi dolezita, obsah textu u jednotlivych roly si na niektorych miestach sam odporuje alebo je nekonzistentny s informaciami v popisoch inych roly, tak isto ako inde aj tu su prvky hovoroveho prejavu, treba text upravit aby bol konzistentny a formalny, bolo by vyborne mat tu aj isty UML Use-Case diagram, ktory graficky popise zasadne opravnenia a funkcie, ku ktorym maju jednotlive pouzivatelske role pristup,

1. sekcia **2.4**, v prvom rade preco je tato sekcia na samostatnej strane?, tu som si vsimol, ze je doplnena bodka za cislo kapitoly, to vyzera, ze dokument, v ktorom ste pracovali ani nema jednotne nastavene styly, za dalsie naco je tam treta uroven vnorenia a este zle ocislovana s odsadenymi nadpismi?, vlastne vsetky odstavce su tu nepochopitelne odsadene, preco?, co sa tyka textu, popisovat ochranu osobnych udajov tym, ze aplikacia dava minimum informacii o ludoch je scestne, za prve by mala aplikacia zobrazovat beznym pouzivatelom iba informacie o sebe a nie informacie o ostatnych pouzivateloch, teda okrem pripadu, ze by ku kurzom malo byt zobrazene meno a kontakt na skolitela, vyssie pouzivatelske role predpokladane budu ludia, ktory absolvovali poucenie o zasadach nakladnia s osobnymi udajmi a preto su povinny tieto udaje sami chranit, to ale neznamena, ze napr. nemozu vidiet udaje o svojich podriadenych ci ucastnikoch kurzov, toto by ste si mali vydiskutovat s Petrou Kopacovou, ake udaje sa zobazuju o kom a akej roly pouzivatela, za dalsie, tu chybaju vseobecne obmedzeznia na system ako taky, mozno nieco o tom, ze system je urceny pre univerzitne prostredie UK a pod.,

1. sekcia **2.5**, obsah sekcie je scela scestny a nepochopeny, sekcia ma obsahovat informacie o predpokladanych prevadzkovych prostrediach, zavislosti aplikacie od platformy a technologii, ktore sa na jej vyvoj a prevadzku budu pouzivat, ano jednou z nich je aj autentifikacia pouzivatelov cez cosign, ale nie jedina,

1. sekcia **3**, hlavna cast popisujuca poziadavky je bohuzial cela zle a musi sa prerobit, resp. poriadne doplnit, ale po poriadku:
    1. co su prosim vas `funkcionalne poziadavky` a este lepsie `nefunkcionalne poziadavky`?, poziadavky su snad `funkcne`, tie druhe budu hadam `nefukncne`?, je dobre, ze ste sa to snazili rozumne rozdelit ale pomenujte to prosim spravne,
    1. co sa jednotlivych poziadaviek tyka, chvalim, ze ste sa ich rozhodli seriozne ocislovat, problem vsak je, ze castokrat je tu iba nazov poziadavky a ziaden detailny popis, niektore poziadavky su delene absurdne, napr `1.1.1 Prihlasenie sa do systemu` delena na `1.1.1.1 Podla mena` a `1.1.1.2 Podla hesla`, co to vobec znamena, preco je to takto delene? znamena to snad, ze pouzivatel sa dokaze autentifikovat iba zadanim mena, pripadne iba zadanim hesla, ze si moze vybrat?,
    1. ako sa ma podla tohoto niekto vyznat, co sa ma implementovat a ako?, akym sposobom ma niekto, ci uz vy alebo zadavatel, na zaklade tohoto dokumentu, vediet povedat, na kolko percent je projekt dokonceny a ako ma vobec niekto vyhodnotit na zaklade tohoto dokumentu spravnost a kvalitu vysledneho produktu?

Celu sekciu 3 treba prerobit poriadne, toto vyzera, ako by ste iba zobrali predbezny zoznam poziadaviek, obalili ho dalsimi sekciami dokumentu (1 a 2) a odovzdali to ako finalny katalog. Je nutne aby ste si k tomu sadli, na niekolko hodin, vsetci, a opravili nedostatky.

Este poznamka na zaver, mozno som to neuvadzal v kazdej sekcii zvlast, aj ked som sa snazil, ale dokument je celkovo napisany v zlom slohovom style, takym hovorovim prejavom, je treba si na to dat pozor a vsetky texty upravit tak, aby boli pisane formalne, najlepsie pomocou autorskeho pluralu a neutralnych viet. Vsetky poziadavky a ich vysvetlenie v sekcii 3 musi byt tzv. jedno-jednoznacne.

Chapem, ze ste necakali takto dlhy kriticky text, ale mojou snahou je docielit, aby vystup vasho projektu bol na urovni, nehovoriac o tom, ze je to velmi dobra priprava pre pisanie vasej zaverecnej prace. Preto prosim objektivne zvazte vsetky pripomienky a zapracujte na nich, v pripade akychkolvek otazok mi napiste (najlepsie sem, nezabudnut na `@` mention).

**Comment by pavelpetrovic** [comment]
pridám aj ja postreh-dva, kým to nemáte v master branch:

prosím, stretol som sa s tým už v minulosti, nepoužívať spojenie "Nefunkčné požiadavky", čo znamená nefungujúce :)
Požiadavky dúfam všetky zafungujú!
"Funkcionálne", čo ste tam mali predtým, sa dalo prežiť, aj keď to tiež nebolo ono, ale nahraďte to, prosím radšej buď spojením "Požiadavky nevzťahujúce sa na funkcionalitu", alebo stačí jednoduché "Ostatné požiadavky". Nemali by to byť ale len všeobecné bonmoty, ale konkrétne veci. A požiadavka typu "možnosť nasadenia na ľubovoľný operačný systém" je predsa nesplniteľná - hádam to len nepobeží na MS DOSe. :) Celkovo by som odporučil tretiu časť zlepšiť, nemal by to byť len zoznam hesiel, ale celé vety. Ak iné požiadavky ako na funkcionalitu zadávateľ nemal, tak tam tá stať nemusí byť, nič v dokumente nemá byť na silu len aby to tam bolo. 
Ďakujem!
p.

**Comment by Saamoot** [comment]
Zdravim,

nedame Vam pokoja ani my a pridavame par pripomienok, informacii a poziadaviek:

### 3.3 Požiadavky na rozhranie - Použivateľské rozhranie
  - prosim "zladovat"(kopirovat vzhlad) treba podla stranky uniba.sk(napr moja.uniba.sk)  nie podla zona FMFI, applikacia je celo-univerzitna (hlavny rozdiel logo)

### Prístup do webovej aplikácie + 2.1 Kontext systému + 2.5 Predpoklady a závislosti
  - v ramci dokumentu je napisane, ze do applikacie sa mozu prihlasovat  bud zamestnanci alebo zamestnanci a studenti poprosil by som Vas toto zjednotit  v dokumente. Do applikacie sa budu moct prihlasit pouzivatelia, ktori budu v databaze, databazu si budeme naplnat my, takze v tomto ohlade nemusite rozlisovat ci je to zamestnanec alebo student.


### 2.4.1 Ochrana osobných údajov + udaje o pouzivatelovi
  - v tejto verzii nema telo no v predchadzajucej verzii ste spominali, ze o pouzivatelovi bude zname iba meno, priezvisko, email. Prosim pridajte aj titul **pred** a **za** menom.

### 2.2 Špecifikácia používateľov - Skolitel + prihlasovanie na kurzy
  - osoby s rolou skolitel a vyssie mozu prihlasit pouzivatela na kurz aj ked nesplna kriteria kurzu, tato funkcionalita je z dovodu, ze pouzivatel moze mat diplom alebo certifikat, tak ak ho skolitel uzna aby ho mohol zapisat

### Prava, specifika role master skolite
  - prosim Vas presunut z `role sub-administrator` moznost vytvarat kurz do `role master skolitel`


### Vytvaranie kurzu + viditelnost kurzu
  - pri vytvarani kurzu je mozne nastavit "pristup", komu bude kurz pristupny
  - nastavit by sa malo dat: 
    - vsetkym
    - jednej alebo viacerim vybranym fakultam
  - toto znamena pre rolu:
    - **pouzivatel az sub-administrator** - pri prezerani kurzov, ak kurz nie je pre vsetkych alebo
      pre fakultu na ktoru osoba s danou rolou patri, kurz sa osobe nezobrazi    
    - **administratora**  - administrator vidi vsetky kurzy bez ohladu na ich obmedzenia

### poziadavka na aplikaciu	- mazanie
  - kazdy zaznam co bude v databaze a bude moznost ho vymazat, namiesto vymazania z databazy prosim implementujte tzv. **soft delete**, cize namiesto toho aby bol nenavratne zmazany sa iba oznaci ako zmazany a nebude sa dalej ozbrazovat v aplikacii


### preformulovat vyrazy
  - `intuitovnost` - toto je velmi zle slovo, kazdy si ho moze vysvetlit inak respektive pre kazdeho je intuitivne nieco ine
  - `jednoznacnost` - prosim napisat coho a popisat ako je to jednoznacne, **napriklad** chyby budu vypisane cervenym textom vo vyskakovacom okne
  - `dostatocne prehladny` - ak je potrebne mat takyto popis prosim napiste co tym myslite, je jasne ze neplanujete davat na stranku neviditelne navigacne prvky, blikajuce nadpisi a nahodne generovane pozicie textov (teda dufam :) ) ale ak planujete nieco specificke co robi webovu stranku prehladnou prosim popiste co

_Tento dokument je pre Vas a nas, takze netreba pouzivat pekne slova, ktore pomahaju predaju aplikacie :)_


----

Ospravedlnujem sa za chaoticke oznacovanie veci, o ktorych hovorim ale kym som sa dostal k napisaniu tohto textu, povodny dokument bol nahradeny `verziou 2` a niektore veci uz v nom neboli ale stali za zmienenie. Dalsia vec preco su popisi take zverske, je ze v aktualnom dokumente `verzie 2` mate viac nasobne popisanu jednu vec z roznych pohladov a tazko sa mi davali dohromady celky.

Takze ak niektore veci nedavaju moc zmysel sa ospravedlnujem, napiste co a pokusim sa to napisat lepsie alebo inak.

**Comment by danasko** [comment]
@Saamoot 
Mám teda ešte otázku ohľadom tej role subadministrátora. 
Na konzultácií so zadávateľkou nám totižto bolo povedané, že subadministrátor je ten, čo vytvára kurzy a priraďuje k nim masterškoliteľov. Ak teda vytváranie kurzov mám presunúť k masterškolitelovi, tak akú funkcionalitu navyše od neho má subadmin?

**Comment by andrejjursa** [comment]
@Saamoot @dandys2 predpokladam, ze subadministrator je admin s "nizsimi pravami", tj. pridelenec k sucasti, ktory ma prava na manazovanie len tejto jemu pridelenej sucasti, Tomas prosim potvrd, ci to je tak (vychadzam z podobnej role na webe UK)

**Comment by marmanova3** [comment]
@andrejjursa @Saamoot 
Ide o to, ze my sme sa presne o tomto explicitne bavili na poslednom stretnuti so zadavatelkou a dospeli sme k tomu, ze subadmin kurzy vytvara (druhy kurzov v jeho sucasti), master skolitel vytvara teminy uz existujucich kurzov (napr. kurz Word) a k nim prideluje skolitelov a skolitel ma pristupy iba k svojmu terminu, ktory moze manazovat.

**Comment by andrejjursa** [comment]
@marmanova3 @Saamoot toto tiez znie rozumne, Tomas vyjasni si to najprv s Petou a potom napis ako to realne je

**Comment by Saamoot** [comment]
@marmanova3 @andrejjursa 
dohodnem sa Petou(zadavatelka) a napisem, finalne znenie. Ospravedlnujem sa za vytvaranie zmatku.

**Comment by andrejjursa** [comment]
@Saamoot pokial mozno cim skor, studentov taketo nejasnosti zdrzuju od povinnosti

**Comment by Saamoot** [comment]
@TIS2017/caviar-it @andrejjursa 

Takze moznost `vytvarat novy kurz` ostava pre rolu `sub-administrator`.

### Pri konzultaci sme narazili na nasledovne veci:
- aky `postup` vytvorenia noveho kurzu pre rolu sub-administratora ste mali na plane?
  - z nasej strany je predstava, ze `sub-administrator` vyvtori prazdny kurz a prideli nanho `master-skolitela`
  - nas postup ale predstavuje problem lebo pouzivatelia uvidia prazdny kurz a preto je potreba pridat moznost `nastavit viditelnosti kurzu`
- v pripade, ze `master-skolite` dlhodobo nebude prace schopny tiez potrebujeme moznost `nastavit viditelnost kurzu` lebo kurz nechceme zrusit ale nema ho kto viest

Takze Vas ziadame o pridanie funckionality `nastavit viditelnost kurzu`.

**Comment by andrejjursa** [comment]
@Saamoot `nastavit viditelnost kurzu` znamena flag `viditelny`/`neviditelny`, alebo nieco zlozitejsie?

**Comment by Saamoot** [comment]
@andrejjursa

Ano ma to by flag `viditelny`/`neviditelny` nastavit ho budu vediet `role "master skolitel" a vyssie`.

**Comment by spisakova31** [comment]
@Saamoot ďakujeme, ešte to doplníme.

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it Pozeram verziu 2.3 katalogu poziadaviek (neviem, ci existuje nejaka novsia):

- Table of contents (obsah) nezodpoveda obsahu dokumentu, zrejme je treba aktualizovat ho rucne, prosim tiez umiestnit nadpis `Obsah` do lava,
- titulna strana by nemala mat cislo 1, cislom 1 ma zacinat strana, kde zacina text dokumentu (tj. `Uvod` momentalne na strane oznacenej 3), toto nie je nieco, co by sa vo Worde nedalo urobit, tak prosim nastavte cislovanie spravne,
- sekcia **1.2** veta `Okrem toho bude systém poskytovať aj možnosť notifikácie používateľa o uvoľnení miesta, v prípade, že je kurz už obsadený.` vobec nedava zmysel, fakt, ze intuitivne rozumiem co ste tym asi chceli povedat neznamena, ze to moze byt napisane takto nepresne, upravte tuto informaciu tak, aby jasne hovorila o tom, co aplikacia robi (pozn. nie je tiez jasne, kto z prihlasenych pouzivatelov moze filtrovat kurzy, aky level na to treba, ked je v aplikacii 6 levelov pouzivatelov), treba to vysvetlit,
- sekcia **1.3** `CIT` je `Centrum informacnych technologii` je to nazov, velke `C`. `PHP` sa pouziva na vyvoj vebovych aplikacii, `HTML` sluzi na tvorbu webovych dokumentov, pri definicii Symfony je preco malym napisane `php`?
- sekcia **1.4** `Odkaz na starú verziu aplikácie` bez `CIT`, neviem preco to tam mate stale tendenciu vkladat,
- sekcia **1.5** `očíslované jedinečným identifikátorom tak, aby sa na ne dalo odvolávať` toto je zbytocna informacia, vymazte ju,
- sekcia **2.1** navrhujem aby ste vetu `Konkrétne je produkt náhradou za predchádzajúcu aplikáciu, ktorá mala približne rovnakú funkcionalitu – tá je ale v aktuálnej aplikácií čiastočne rozšírená.` napr. ako: `Vyvyjana aplikacia bude nahradou za existujucu aplikaciu, nova verzia bude obsahovat rozsirenu funkcionalitu.`,
- sekcia **2.2** pri precitani prveho odstavca som si spomenul na 6 roly pouzivatelov, o ktorych sa pisalo vyssie, ale tu je roly iba 5, ako to teda je?
- sekcia **2.2** navrhujem zmenit `ktorá sa v hierarchii nachádza pod ňou` na `ktora sa nachadza na nizsej urovni v hierarchii`,
- sekcia **2.2** tiez by bolo rozumne zmenit vetu `Teda okrem svojich používateľských práv má aj práva všetkých typov používateľov, ktorí sú od nej nižšie.` na nieco v zmysle `Pouzivatelska rola na vyssej urovni zahrna vsetky opravnenia pouzivatelskych roly na nizsej urovni.`,
- sekcia **2.2** posledna poznamka: v roznych rolach sa pise, ze pouzivatel je urceny rolou nad nim, prvy odstavec tejto sekcie ale hovori, ze pouzivatel na vyssej urovni dedi vsetky prava pouzivatelov na nizsej urovni, teda tieto definicie si odporuju, skuste to trochu premysliet, ako to napisat tak, aby tam tento nesulad nebol,
- sekcia **2.3** ziadna chyba tu zda sa nie je, len ma napadlo, skuste zvazit ci by nebolo konzistentnejsie so zviskom dokumentu ak by boly roly pouzivatelov opat vypisane od administratora nizsie,
- sekcia **2.4** v podstate tu stale chyba to, co som chcel aby ste doplnili pri hodnoteni predchodzej verzie dokumentu,
- sekcia **2.5** fungovanim na vsetkych beznych operacnych systemoch je myslene co? akoze na webserveroch spustanych na tychto platformach alebo ma klientska cast aplikacie spravne fungovat na tychto platformach?, vysvetlite to v texte poriadne,
- sekcia **3** k 1.1.3 by som sa chcel spytat, ak pouzivatel nesplna prerekvizitu, tak kurz neuvidi, ale ako potom moze byt na kurz aj tak prihlaseny (predpokladam, ze musi o to sam prejavit zaujem) tym, ze mu skolitej uzna certifikat alebo diplom?
- sekcia **3** k 1.1.5 mam otazku, pouzivatel sa moze odhlasit hocikedy, aj tesne pred konanim kurzu? nie je tam ziadna casova rezerva pred zaciatkom samotneho terminu kurzu, v ktorej uz nie je mozne sa odhlasovat (otazka totiz smeruje ku konzistencii napr. zoznamu prihlasenych ludi na kurz, ktory si v nejakom casovom bode moze vytlacit skolitel - aspon niekde som to v texte cital, ze toto vie spravit - ci sa myslelo na moznost, ze by skolitel vdaka odhlaseniu pouzivatela potom, co si vytlaci zoznam, sa mohol dostat do situacie, ze tento nie je rovnaky ako zaznami v databaze), este jedna vec na zamyslenie, tato poziadavka ani nespecifikuje odhlasovane sa z kurzu po zaciatku terminu kurzu (tj. pridem na kurz, absolvujem a potom sa odhlasim?),
- sekcia **3** poziadavka 1.2.2 sa niekam stratila?
- sekcia **3** otazka k 1.3.2 priradeny skolitel podla tejto poziadavky po priradeni k terminu kurzu vie spravovat cely kurz, nema on ale pravo na to pracovat len s priradenym terminom?
- sekcia **3** prava administratora: niektore kurzy ako som pochopil, su celouniverzitne, o tom, ci existuje variant kurzu pre niekolko zvolenych sucasti, neviem, kazdopadne na taketo nieco by mal mat zrejme prava hlavny administrator, ci?
- sekcia **3** vetu `Pozn. každá ďalšia rola je nadstavbou predchádzajúcich, teda vie robiť všetko, čo všetky nad ňou dohromady.` prepiste prosim na nieco v tvare `Poznamka: kazda rola dedi vsetky opravnenia roly nizsie v hierarchii.",
- sekcia **3** v 1.6.2 by bolo lepsie upravit slovosled z `termín (dátum a čas), konania` na `termín konania (dátum a čas)`, a `max.` prepisat na cele slovo, tj. `maximalnu`,
- sekcia **3.2** opat obsahuje zoznam, kde prvky nekoncia ciarkou, naviac je velmi kostrbaty, niektore poziadavky v nom nemaju charakter poziadaviek, celkovo tento zoznam vyzera ako citovanie slovnika, ked uz napr. pisete o bezpecnosti a ochrane osobnych udajov tak AKO? ma toto aplikacia riesit, preco riesite nejaku portabilitu, ked aplikacia ma byt hostovana na debiane? spolahlivost je snad implicitna, naco to tu je?
- sekcia **3.3** poziadavka 3.1.3 nie je samovysvetlujuca, ako ma aplikacia dosiahnut tuto poziadavku, treba to popisat.

Nakoniec vas prosim, aby ste si dokument po sebe precitali a upravili vety, ktore maju zjavne hovorovy styl na styl zodpovedajuci technickej dokumentacii.

**Comment by marmanova3** [comment]
Ostalo na doriešenie:

- [x] sekcia 2.2 posledna poznamka: v roznych rolach sa pise, ze pouzivatel je urceny rolou nad nim, prvy odstavec tejto sekcie ale hovori, ze pouzivatel na vyssej urovni dedi vsetky prava pouzivatelov na nizsej urovni, teda tieto definicie si odporuju, skuste to trochu premysliet, ako to napisat tak, aby tam tento nesulad nebol,

- [x] sekcia 2.4 v podstate tu stale chyba to, co som chcel aby ste doplnili pri hodnoteni predchodzej verzie dokumentu,

- [x] sekcia 2.5 fungovanim na vsetkych beznych operacnych systemoch je myslene co? akoze na webserveroch spustanych na tychto platformach alebo ma klientska cast aplikacie spravne fungovat na tychto platformach?, vysvetlite to v texte poriadne,

- [x] sekcia 3.2 opat zoznam je velmi kostrbaty, niektore poziadavky v nom nemaju charakter poziadaviek, celkovo tento zoznam vyzera ako citovanie slovnika, ked uz napr. pisete o bezpecnosti a ochrane osobnych udajov tak AKO? ma toto aplikacia riesit, preco riesite nejaku portabilitu, ked aplikacia ma byt hostovana na debiane? - @dandys2 @spisakova31 @MisooB  Vieme niečo o tom, že to má byť hostované na debiane?

- [x] sekcia 3.3 poziadavka 3.1.3 nie je samovysvetlujuca, ako ma aplikacia dosiahnut tuto poziadavku, treba to popisat.

- [x] pridať požiadavku na flag viditeľný/neviditeľný

**Comment by danasko** [comment]
@marmanova3  no teraz uz vieme.. 😄

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it poslite to @Saamoot (Tomasovi) na kontrolu, aby vam dokument schvalil alebo dal pripomienky.

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it dostal som info od zadavatelky, ze katalog je z ich strany ok, dajte ho do repozitara (master branch) a tento issue mozete zatvorit.
