### ISSUE TITLE
Tvorba návrhu systému

### ISSUE THREAD

**Issue by marmanova3** [TIS2017/Kurzy#8]
- dopísať 1.4 - čo sa nachádza vo zvyšku dokumnetu
- Module decomposition: controllery - role (admin, používateľ...), používatelia a ich oprávnenia
- Data decomposition: entity (UML diagram)
- Dependency description: technólogie
- Module interface: aké majú controllery metódy a aké majú vstupné parametre
- Process interface: sekvenčný diagram
- Detailed design: GUI

**Comment by marmanova3** [comment]
@andrejjursa @Saamoot Nahrali sme návrh systému. Môžete sa na to, prosím Vás, pozrieť a skritizovať (**nie veľmi**, prosím)?

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it pozrel som si vas dokument a dopisal som don pripomienky, bohuzial niektore casti su cele zle, vid. [anotovany dokument](https://www.dropbox.com/s/q7g1z0vbo4f610y/kurzy_navrh_systemu_1_anotovany.pdf?dl=0).

**Comment by danasko** [comment]
@andrejjursa 
Studovali sme si technologie, ake su komponenty v symfony a prisli sme s tymto navrhom dekompozicie. Keby ste nam k tomu mohli dat konstruktivnu kritiku resp. rady co zlepsit a ako.., dakujeme.

**Comment by andrejjursa** [comment]
@dandys2 ano, skusim sa k tomu zajtra dostat

**Comment by andrejjursa** [comment]
@TIS2017/caviar-it Prosim vas skuste mi vysvetlit zmysel delenia controllerov podla typu pouzivatelskej role. Co v tych controlleroch bude?

Dalej, preco je vazba medzi security a form komponentom a nie medzi security a controller?

Potom, co znamenaju tie formularove komponenty, to su komponenty na konkretne, ktore formulare?

Viete o tom, ze hromadne odosielanie emailov sa deje na pozadi cez CRON, tj. niekde bude treba mat aj console component a vazbu medzi nim a swift mailer, pricom bude existovat aj vazba medzi console a twig.

Tie Twig template komponenty su vlastne co? A preco su len tieto dva?

Posledna otazka, ktora je velmi dolezita a nic zle nou nesledujem, ak by sa to tak javilo, je, ci uz niekto z vas niekedy tvoril nejaky software postaveny na webovej model-view-controller architekture?

**Comment by marmanova3** [comment]
@andrejjursa 
Nie, nikto z nás nikdy predtým:
- netvoril informačný systém - vôbec nie v takomto rozsahu,
- netvoril software postavený na webovej mvc architektúre,
- nepoužíval symfony, twig, doctrine a skoro vôbec ani php a mysql,
- dokonca nepoužíval ani žiaden iný framework,
- nevie o tom, že hromadne odosielanie emailov sa deje na pozadí cez CRON,
- nevie čo je CRON,
- a už vôbec nevidel čo sú to komponenty, ako sa skladajú a ako sa robí dekompozícia systému.
O dekompozícii vieme iba to, čo sme sa dočítali na inetnete v posledných dňoch - týždňoch, resp. v radách, ktoré ste dali nám alebo iným tímom. Našli sme, že komponenty sú všetko, od kontrolerov, cez entity až po repository a pod. Mysleli, sme, že každá rola bude mať vlastnú triedu - kontroler a bude dediť od predchádzajúcich. Preštudovali sme si symfony dokumentáciu a všetko čo sme našli k téme. Žiaľ, nevieme sa naučiť behom zopár týždňov z čítania dokumentácie, resp. skúšania zakladania nejakých basic projektíkov popri výučbových videjkách, pochopiť systém, s ktorým sme nikdy nepracovali. Strávili sme nad tým celé hodiny, ale obávam sa, že pokiaľ nám bližšie nevysvetlíte ako to funguje, budeme to musieť ďalej robiť iba pokusom-omylom.

**Comment by andrejjursa** [comment]
Najlepsie bude ak si to skusime cele v piatok prejst spolu a vysvetlit.

**Comment by marmanova3** [comment]
Súhlasím, ďakujeme.

**Comment by danasko** [comment]
@andrejjursa Prerobili sme dekompoziciu komponentov..
