### ISSUE TITLE
Návrh databázového modelu

### ISSUE THREAD

**Issue by marmanova3** [TIS2017/Kurzy#9]
- vytvoriť entitno-relačný model databázy
- vytvoriť relačný model databázy
- naučiť sa pracovať s doctrine
- vyrobiť CREATE script

**Comment by marmanova3** [comment]
@dandys2 @MisooB @spisakova31  
Skontrolujte ma, prosím, že či som sa niekde nesekla. Tiež treba preveriť, že ako fungujú typy v MySQL, respektíve či sa líšia od PostrgeSQL. Konkrétne som si neni istá tým varchar v textoch.

**Comment by marmanova3** [comment]
Mal by nám stačiť varchar, za predpokladu, že description kurzu nebude mať viac ako 65,535 znakov.

**Comment by danasko** [comment]
az take zaujimave tie kurzy hadam nebudu..

**Comment by spisakova31** [comment]
:D Danka, the pessimist...

**Comment by pavelpetrovic** [comment]
dievčence a mládenec, Váš projekt je, ak dobre sledujem komunikáciu, medzi tými, čo postupujú hladko vpred, vďaka za dobrú prácu doteraz, čaká vás ešte kus práce, vydržte tak aj naďalej.

**Comment by spisakova31** [comment]
Patka, este nieco treba prerobit, alebo mozeme uzavriet issue? :-)

**Comment by marmanova3** [comment]
@spisakova31 Pokiaľ viem, ešte tam nie je verzia databázového systému, ktorá by obsahovala aj tie cudzie kľúče. Nebavili sa na stretnutí s cvičiacim, že to ešte M dorobí a pozrú to budúci piatok?

**Comment by MisooB** [comment]
@marmanova3 Bavili. Dorobim to a potom to v piatok pozrieme cele.

**Comment by spisakova31** [comment]
@marmanova3  mas pravdu, na ten create script som nejak zabudla, ze patri sem... nic som nepovedala O:-)

**Comment by marmanova3** [comment]
@Saamoot 
@andrejjursa nám v anotovanom dokumente pre návrh systému písal, že boli nejaké pripomienky k názvom tabuliek "hard_prerequisites" a "parts". My však o ničom takom nevieme, tak sa chcem spýtať, že či je s názvami problém, prípadne aké by boli preferované.

**Comment by andrejjursa** [comment]
@marmanova3 spomynam si, ze @Saamoot chcel premenovat tabulku `parts` na `workplaces`, niekde k tomu aj pisal pripomienku ale zjavne nie na github, snad sa nemylim, Tomas mozes to prosim potvrdit?

**Comment by Saamoot** [comment]
@andrejjursa @marmanova3 
Vzhladom na polozenu otazku mam pocit ako keby sa stratili moje pripomienky na navrh databazy co som poslal andrejovi, tak ich sem prilozim:

```
- nazvy:
  - types_of_courses -> course_types
  - instances_of_courses -> courses_instances
  - part -> workplaces
  - hard_prerequisities -> course_hard_prerequisities
  - `hard_prerequisities`.`course` -> `hard_prerequisities`.`type_of_course_id`
  - `hard_prerequisities`.`prerequisite` -> `hard_prerequisities`.`required_type_of_course_id`
  - `users`.`user_name` -> `users`.`login`
  * a teda upravit aj nazvy stlpcov, ktore "ukazuju" na tabulky a prepojovacich(relacnych) tabuliek

- co to pouzivaju za typ stlpca serial ? (preco nie interger ???)
- je tabulka subadmins potrebna ?
  - nestaci -> parts <-> user_part <-> user <-> role ??

- soft prerequisities
  - ako stlpec varchar v tabulke by bolo podla mna lepsie to mat v tabulke:
    - nazov napr.: course_soft_prerequisities, zo stlpcami
      - id integer
      - type_of_course_id integer
      - value varchar


na zvazenie:
  - premenovat z `types_of_courser`.`garant` na `types_of_courser`.`garant_user_id`
  - premenovat z `instances_of_courses`.`supervisor` na `instances_of_courses`.`supervisor_user_id`
  - premenovat z `instances_of_courses`.`type_of_course` na `instances_of_courses`.`type_of_course_id`
  - pridat stlpec `enrolled`.`attended` aby bolo mozne zistit ci tam bol alebo nie (ked bude graduated false)
  - upravit `instances_of_courses`.`place` z `varchar` na `interger` (place_id)
    - a mat samostatnu tabulku `places` (zle meno zatial len idea) aby sa popripade, k miestam dali pridat neskor dalsie informacie
```
Ak ste tie veci uz riesili tak pripomienky nerieste.

Po precitani komentarov som narazil na jednu vec a to pri otazke na typ stlpca `description` pre kurz. Prosim pouzite typ `text` ak by vam to prislo malo existuje `longtext`.

Ak by bolo mozne mozte niekde na githube napisat linky, kde mate poukladane dokumenty(v tomto pripade navrh databazy) ?

**Comment by marmanova3** [comment]
@Saamoot 
Žiadne pripomienky sme od @andrejjursa, žiaľ, neobdržali. Už sme vyrobili okrem všetkých návrhov aj tabuľky v databáze a budeme musieť všetko prerábať.
K pripomienkam:
1. názvy stĺpcov môžme zmeniť, 
2. typ serial je integer auto-increment,
3. tabuľka subadmins existuje ako väzobná, keďže jedna súčasť môže mať viacero subadminov,
4. nie som si celkom istá, že prečo by bolo praktickejšie mať pre ne samostatnú tabuľku, keďže predpokladám, že to je nejaký text, kde školiteľ napíše napr. "Je potrebné mať notebook." alebo "Prineste si teplé oblečenie, nekúrime." a nie niekoľko opakujúcich sa možností, z ktorých sa bude voliť. Táto tabuľka by sa len plnila a potom by sa z nej ťahalo? Ak pre ňu nie je nejaká vážna príčina, tak nevidíme dôvod to implementovať takto.
5. Premenovať stĺpce môžeme,
6. tabuľka "places" by si vyžadovala počiatočné naplnenie a potom možnosť vyberať z už existujúcich možností, alebo možnosť ďalej prídavať nové miesta, čo je ďalšia implementácia navyše, ktorá nám príde momentálne zbytočná,
7. description zmeníme na text, resp. longtext.

**Comment by andrejjursa** [comment]
:( tak asi som tie pripomienky dostal emailom a nepreposlal, prepacte, asi mi do toho prislo nieco ine a zabudol som na to.

> Po precitani komentarov som narazil na jednu vec a to pri otazke na typ stlpca description pre kurz. Prosim pouzite typ text ak by vam to prislo malo existuje longtext.

Len ma napadlo ci `description` nie je klucove slovo, radsej to skontrolujte, potom by sa tak stlpec volat nemal.

**Comment by Saamoot** [comment]
@marmanova3 

- ohladom prerabania tabuliek ma to mrzi, @andrejjursa Vam nespominal migracie ? Ked som s nim robil projekt vyuzili sme migracie a robit zmeny neboli velmi bolestive resp. sa dali aplikovat ako "update".

4, zmysel to ma taky, aby sa aplikacia v buducnosti dala lahsie rozsirovat, napr na tvojom priklade, `"Je potrebné mať notebook."`, keby vznikne poziadavka aby sa dali k notebookom vyberat parametre hardware-u alebo potreba mat serial port tak by sa to dalo iba textovo co nie je problem do momentu ked to bude potreba spravovat. V tedy budu data v ako text, co prida vela roboty aby sa s nimi dalo pracovat.

6, existuju aj riesenia, ktore nevyzaduju pociatocne naplnenie a stale vedia poskytnut potrebnu funkcionalitu. Vyber miestnosti nemusi byt len select, ale napriklad input + select (aka combobox) a to by vedelo posluzit na vyberanie(+autocomplete) aj vytvaranie. Pre Vas to je momentalne mozno zbytocne ale ci to bude pravda nastalo sa neda povedat, preto je dobre databazu navrhnut tak aby sa dala dalej rozsirovat.

Pri navrhovani databazy sa oplati dodrzat par veci konkretne [database normalization](https://en.wikipedia.org/wiki/Database_normalization). Ak nie som moc mimo tak by nemal byt problem navrhnut databazu sposobom ako navrhujem ja ale netreba vytvorit nove pouzivatelske(spravcovske) rozhrania => Nebude problem v buducnosti rozsirovat applikaciu a pre Vas by to malo byt menej novej roboty.

**Comment by andrejjursa** [comment]
@Saamoot @marmanova3 @TIS2017/caviar-it som si isty, ze som spomynal [doctrine migrations bundle](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html) (pozn. tutorial je pre symfony 2 ale bundle je samostatny balik, ktory staci pridat do aplikacie a ten setup je plus-minus rovnaky).

**Comment by spisakova31** [comment]
@Saamoot  prosim ta, vies mi povedat konkretnejsie ake stlpce by mali byt v tej novej tabulke 'Places'?

**Comment by Saamoot** [comment]
@spisakova31 

`places`
- id [integer] AI
- name [varchar(32)]
- workplace_id *1 [integer]
- building/building_id [varchar(32)/integer] `*1`
- created [TIMESTAMP]
- updated [TIMESTAMP]
- deleted [boolean/tinyint]


Toto je predstava co by som tam chcel mat. 
Ohladom stlpca `*1 building` - tento by som tam chcel mat ale zatial ma nenapadla implementacia v existujucom prostredi bez toho aby sa vytvorili nove pouzivatelske rozhrania.
